FROM node:latest

ENV HOME /home/current
RUN mkdir -p $HOME
WORKDIR $HOME

RUN apt-get update && apt-get install apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    cat /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install vim -y && \
    apt-get install yarn -y
